### PR TITLE
Fixed the missing set max frame size

### PR DESCRIPTION
**Pull request by michli**
There were double max buffer size setting. One of them shall be max frame size setting.

### CODE REVIEW

**Comment by jfarcand** [comment]
Thanks! Do you need an official release?

**Comment by michli** [comment]
Yes, that would be nice.

**Comment by michli** [comment]
Will you cut a release soon, like "1.4.1"? Otherwise, I'll have to push it to our own nexus.

**Comment by jfarcand** [comment]
@michli back from vacation. I will release 1.5.0 this week. OK?

**Pull request merged**
